namespace Bolt.Client.Channels
{
    /// <summary>
    /// The Generic variant of <see cref="ContractProxy"/> class.
    /// </summary>
    /// <typeparam name="TContractDescriptor">The strongly typed contract descriptor usually generated by Bolt.</typeparam>
    public abstract class ContractProxy<TContractDescriptor> : ContractProxy
        where TContractDescriptor : ContractDescriptor
    {
        protected ContractProxy(ContractProxy proxy)
            : base(proxy)
        {
        }

        protected ContractProxy(IChannel channel)
            : base(ContractDescriptor<TContractDescriptor>.Instance, channel)
        {
        }

        public new TContractDescriptor Descriptor
        {
            get { return (TContractDescriptor)base.Descriptor; }
            set { base.Descriptor = value; }
        }
    }
}
