namespace Bolt
{
    /// <summary>
    /// Defines well known errors generated by server or client.
    /// </summary>
    public enum ServerErrorCode
    {
        /// <summary>
        /// Unknown error occurred.
        /// </summary>
        Unknown = 0,

        /// <summary>
        /// Error occurred during serialization of response.
        /// </summary>
        ResponseSerialization = 1,

        /// <summary>
        /// Error occurred during deserialization of request.
        /// </summary>
        ParameterDeserialization = 2,

        /// <summary>
        /// The action defined in request url for specific contract was not found.
        /// </summary>
        ActionNotFound = 3,

        /// <summary>
        /// The contract defined in request url was not found.
        /// </summary>
        ContractNotFound = 4,

        /// <summary>
        /// The action is not implemented on server.
        /// </summary>
        ActionNotImplemented = 5,

        /// <summary>
        /// The action requires session id but session header was not found.
        /// </summary>
        NoSessionHeader = 6,

        /// <summary>
        /// The session id was extracted from headers but the session was not found on server.
        /// </summary>
        SessionNotFound = 7,

        /// <summary>
        /// The session id was expected to be received from server but none was found.
        /// </summary>
        SessionIdNotReceived = 8,

        /// <summary>
        /// The server is unavailable.
        /// </summary>
        BoltUnavailable = 9,

        ContractInstanceNotFound = 10,

        ExceptionSerialization = 11
    }
}
